version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./build
      dockerfile: php74.dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./site:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=secret
    